### PR TITLE
fixing this stupid program

### LINKED ISSUE #1: please rename file1 variable
https://github.com/smulhall1337/misc/blob/ab7eb9b088b73c5b4b4a0da0e42bd3f14896adbb/file-diff.py#L5

i really don' lt like the name

### PR DESCRIPTION
**Pull request by jasonwalsh**
ok

### CODE REVIEW

**Comment by jasonwalsh** [comment]
#1

**Comment by jasonwalsh** [comment]
resolves #1

**Comment by jasonwalsh** [comment]
@smulhall1337

**Comment by jasonwalsh** [comment]
@smulhall1337 can you plea se merge this?
.
.
.

**Comment by jasonwalsh** [comment]
https://stallman.org/

**Comment by smulhall1337** [comment]
`with open(sys.argv[1], 'r') as f_i_l_e_o_n_e:`

this is unacceptable the current convention is UPPER_SNAKE_CASE

**Comment by jasonwalsh** [comment]
@smulhall1337 ok

**Comment by smulhall1337** [comment]
https://stallman.org/republican-election-rigging.html

**Pull request merged**
